set(_osg_requested_components ${OpenSceneGraph_FIND_COMPONENTS})
if(NOT _osg_requested_components)
    set(_osg_requested_components osg osgDB osgUtil osgGA osgText osgAnimation)
endif()

set(_osg_unofficial_components)
if("plugins" IN_LIST _osg_requested_components)
    list(APPEND _osg_unofficial_components plugins)
endif()

set(_osg_config_hints)
if(DEFINED VCPKG_INSTALLED_DIR AND DEFINED VCPKG_TARGET_TRIPLET)
    list(APPEND _osg_config_hints "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/unofficial-osg")
endif()
foreach(_prefix IN LISTS CMAKE_PREFIX_PATH)
    list(APPEND _osg_config_hints "${_prefix}/share/unofficial-osg")
endforeach()

find_file(_unofficial_osg_config
    NAMES unofficial-osg-config.cmake
    HINTS ${_osg_config_hints}
    NO_DEFAULT_PATH
)

if(_unofficial_osg_config)
    if(_osg_unofficial_components)
        set(unofficial_osg_FIND_COMPONENTS ${_osg_unofficial_components})
    endif()
    include("${_unofficial_osg_config}")
    set(_unofficial_osg_found TRUE)
endif()

if(_unofficial_osg_found)
    set(_osg_target_map_OpenThreads unofficial::osg::OpenThreads)
    set(_osg_target_map_osg unofficial::osg::osg)
    set(_osg_target_map_osgDB unofficial::osg::osgDB)
    set(_osg_target_map_osgUtil unofficial::osg::osgUtil)
    set(_osg_target_map_osgGA unofficial::osg::osgGA)
    set(_osg_target_map_osgText unofficial::osg::osgText)
    set(_osg_target_map_osgViewer unofficial::osg::osgViewer)
    set(_osg_target_map_osgAnimation unofficial::osg::osgAnimation)
    set(_osg_target_map_osgFX unofficial::osg::osgFX)
    set(_osg_target_map_osgManipulator unofficial::osg::osgManipulator)
    set(_osg_target_map_osgParticle unofficial::osg::osgParticle)
    set(_osg_target_map_osgUI unofficial::osg::osgUI)
    set(_osg_target_map_osgVolume unofficial::osg::osgVolume)
    set(_osg_target_map_osgShadow unofficial::osg::osgShadow)
    set(_osg_target_map_osgSim unofficial::osg::osgSim)
    set(_osg_target_map_osgTerrain unofficial::osg::osgTerrain)
    set(_osg_target_map_osgWidget unofficial::osg::osgWidget)
    set(_osg_target_map_osgPresentation unofficial::osg::osgPresentation)

    set(OPENSCENEGRAPH_LIBRARIES)
    set(OPENSCENEGRAPH_INCLUDE_DIRS)
    set(OPENSCENEGRAPH_FOUND TRUE)
    set(OPENSCENEGRAPH_INCLUDE_DIR TRUE)

    foreach(_component IN LISTS _osg_requested_components)
        if(DEFINED _osg_target_map_${_component})
            set(_target "${_osg_target_map_${_component}}")
            if(TARGET "${_target}")
                list(APPEND OPENSCENEGRAPH_LIBRARIES "${_target}")
                get_target_property(_target_includes "${_target}" INTERFACE_INCLUDE_DIRECTORIES)
                if(_target_includes)
                    list(APPEND OPENSCENEGRAPH_INCLUDE_DIRS ${_target_includes})
                endif()
                string(TOUPPER "${_component}" _component_upper)
                set(${_component_upper}_FOUND TRUE)
            else()
                set(OPENSCENEGRAPH_FOUND FALSE)
            endif()
        endif()
    endforeach()

    list(REMOVE_DUPLICATES OPENSCENEGRAPH_LIBRARIES)
    list(REMOVE_DUPLICATES OPENSCENEGRAPH_INCLUDE_DIRS)

    if(OPENSCENEGRAPH_FOUND)
        list(GET OPENSCENEGRAPH_INCLUDE_DIRS 0 OPENSCENEGRAPH_INCLUDE_DIR)
        set(OSG_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSG_LIBRARY unofficial::osg::osg)
        set(OSGDB_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSGDB_LIBRARY unofficial::osg::osgDB)
        set(OSGUTIL_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSGUTIL_LIBRARY unofficial::osg::osgUtil)
        set(OSGGA_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSGGA_LIBRARY unofficial::osg::osgGA)
        set(OSGTEXT_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSGTEXT_LIBRARY unofficial::osg::osgText)
        set(OSGANIMATION_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OSGANIMATION_LIBRARY unofficial::osg::osgAnimation)
        set(OPENTHREADS_INCLUDE_DIR ${OPENSCENEGRAPH_INCLUDE_DIR})
        set(OPENTHREADS_LIBRARY unofficial::osg::OpenThreads)
        set(OpenSceneGraph_FOUND TRUE)
        set(OpenSceneGraph_VERSION 3.6.5)
        set(OPENSCENEGRAPH_VERSION 3.6.5)
        return()
    endif()
endif()

include("${CMAKE_ROOT}/Modules/FindOpenSceneGraph.cmake")
